# Generated by Django 3.0.5 on 2020-04-17 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Heroe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('sexo', models.CharField(max_length=10)),
                ('altura', models.FloatField()),
                ('fecha_registro', models.DateField()),
                ('habilidades', models.CharField(max_length=200)),
                ('edad', models.IntegerField()),
            ],
        ),
    ]
